### ISSUE TITLE
How to initialize and run?

### ISSUE THREAD

**Issue by J-XZ** [lei-houjyu/RubbleDB#1]
Could you please guide me on how to initialize and run RubbleDB? The documentation in the codebase contains conflicting and confusing information. For instance, the setup for the parameters of the `eval.sh` script at [this location](https://github.com/lei-houjyu/YCSB/blob/605558c5b79810d50327f04a5b6a5ca1f274a315/README.md?plain=1#L67) contradicts the description at [this location](https://github.com/lei-houjyu/YCSB/blob/605558c5b79810d50327f04a5b6a5ca1f274a315/eval.sh#L6). Additionally, there are no instructions on how to initialize the NVMe-oF connection between nodes in the documentation. I tried to use the [setup-rubble.sh](https://github.com/lei-houjyu/rocksdb/blob/e8fbf3a9455951a83dbff44c083e02c3661c1f9f/rubble/setup-rubble.sh#L158) script for initialization, but the file paths set in the script conflict with those mentioned at [this location](https://github.com/lei-houjyu/YCSB/blob/605558c5b79810d50327f04a5b6a5ca1f274a315/README.md?plain=1#L41), preventing correct execution.

I also attempted the method described in the documentation at [this location](https://github.com/lei-houjyu/rocksdb/blob/e8fbf3a9455951a83dbff44c083e02c3661c1f9f/rubble/docs/instructions.md?plain=1#L1), but it still didn't work.

Could you please advise on the sequence in which I should read the markdown documents in the codebase? Alternatively, what order should I follow, and which executable files or scripts and parameters should I use to initialize the nodes and run a complete YCSB test?

My execution environment consists of four r6525 nodes in CloudLab. I am using node0 as the client and node1 through node3 as servers, as described in the documentation at [this location](https://github.com/lei-houjyu/YCSB/blob/605558c5b79810d50327f04a5b6a5ca1f274a315/README.md?plain=1#L13). Is this setup appropriate?

**Comment by lei-houjyu** [comment]
Hi @J-XZ, documents in submodules might be outdated. This main repo also pointed to stale commits before, and I guess that's why it didn't work for you. I have updated the submodules to their latest commits and added in `README.md` steps to build and run RubbleDB on CloudLab. Please refer to it and let me know if you have any issues. Thanks!
